// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.21.12
// source: game_input.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Any } from "./google/protobuf/any";
import Long = require("long");

export const protobufPackage = "game_input";

export interface ClientInput {
  senderId: number;
  gameInputMessage: Any | undefined;
}

function createBaseClientInput(): ClientInput {
  return { senderId: 0, gameInputMessage: undefined };
}

export const ClientInput = {
  encode(message: ClientInput, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.senderId !== 0) {
      writer.uint32(8).uint64(message.senderId);
    }
    if (message.gameInputMessage !== undefined) {
      Any.encode(message.gameInputMessage, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ClientInput {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.senderId = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.gameInputMessage = Any.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientInput {
    return {
      senderId: isSet(object.senderId) ? globalThis.Number(object.senderId) : 0,
      gameInputMessage: isSet(object.gameInputMessage) ? Any.fromJSON(object.gameInputMessage) : undefined,
    };
  },

  toJSON(message: ClientInput): unknown {
    const obj: any = {};
    if (message.senderId !== 0) {
      obj.senderId = Math.round(message.senderId);
    }
    if (message.gameInputMessage !== undefined) {
      obj.gameInputMessage = Any.toJSON(message.gameInputMessage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientInput>, I>>(base?: I): ClientInput {
    return ClientInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientInput>, I>>(object: I): ClientInput {
    const message = createBaseClientInput();
    message.senderId = object.senderId ?? 0;
    message.gameInputMessage = (object.gameInputMessage !== undefined && object.gameInputMessage !== null)
      ? Any.fromPartial(object.gameInputMessage)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
