// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameMessage {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<::prost_types::Any>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameDirectOutput {
    #[prost(uint64, tag = "1")]
    pub receiver_id: u64,
    #[prost(message, optional, tag = "2")]
    pub game_output: ::core::option::Option<GameMessage>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameOutput {
    #[prost(message, repeated, tag = "1")]
    pub direct_messages: ::prost::alloc::vec::Vec<GameDirectOutput>,
    #[prost(message, optional, tag = "2")]
    pub broadcast: ::core::option::Option<GameMessage>,
}
