// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FfxivCharacterSelectionInput {
    #[prost(uint64, optional, tag = "1")]
    pub select_character_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub select_role_id: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "10")]
    pub ready: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "20")]
    pub please_repeat: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "90")]
    pub internal: ::core::option::Option<::prost_types::Any>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FfxivCharacterSelection {
    #[prost(message, repeated, tag = "1")]
    pub characters_data: ::prost::alloc::vec::Vec<FfxivPlayerCharacter>,
    #[prost(message, repeated, tag = "2")]
    pub raid_roles_data: ::prost::alloc::vec::Vec<FfxivPlayerRaidRole>,
    #[prost(uint64, repeated, tag = "10")]
    pub taken_raid_role_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, optional, tag = "20")]
    pub selected_character_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "21")]
    pub selected_role_id: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "30")]
    pub correct: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "31")]
    pub user_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "32")]
    pub user_warning: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "33")]
    pub user_error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "90")]
    pub internal: ::core::option::Option<::prost_types::Any>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FfxivPlayerCharacter {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub avatar_asset: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub job: ::core::option::Option<FfxivPlayerJob>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FfxivPlayerRaidRole {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name_short: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub class: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FfxivPlayerJob {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name_short: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub class: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub icon_asset: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
    #[prost(uint64, repeated, tag = "7")]
    pub fit_raid_role_ids: ::prost::alloc::vec::Vec<u64>,
}
