// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FfxivGameOutput {
    #[prost(message, optional, tag = "1")]
    pub scene_update: ::core::option::Option<super::game_renderer::SceneUpdate>,
}
