// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Float32Array {
    #[prost(float, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Uint32Array {
    #[prost(uint32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Texture {
    #[prost(uint32, tag = "1")]
    pub bind_offset: u32,
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UniformAttributes {
    #[prost(map = "string, message", tag = "1")]
    pub float: ::std::collections::HashMap<::prost::alloc::string::String, Float32Array>,
    #[prost(map = "string, message", tag = "2")]
    pub vec2: ::std::collections::HashMap<::prost::alloc::string::String, Float32Array>,
    #[prost(map = "string, message", tag = "3")]
    pub vec3: ::std::collections::HashMap<::prost::alloc::string::String, Float32Array>,
    #[prost(map = "string, message", tag = "4")]
    pub vec4: ::std::collections::HashMap<::prost::alloc::string::String, Float32Array>,
    #[prost(map = "string, message", tag = "5")]
    pub int: ::std::collections::HashMap<::prost::alloc::string::String, Uint32Array>,
    #[prost(map = "string, message", tag = "6")]
    pub ivec2: ::std::collections::HashMap<::prost::alloc::string::String, Uint32Array>,
    #[prost(map = "string, message", tag = "7")]
    pub ivec3: ::std::collections::HashMap<::prost::alloc::string::String, Uint32Array>,
    #[prost(map = "string, message", tag = "8")]
    pub ivec4: ::std::collections::HashMap<::prost::alloc::string::String, Uint32Array>,
    #[prost(map = "string, message", tag = "9")]
    pub mat4: ::std::collections::HashMap<::prost::alloc::string::String, Float32Array>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VertexAttributes {
    /// Mandatory
    #[prost(string, tag = "1")]
    pub vertices: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub named_buffers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DrawBundle {
    #[prost(uint32, optional, tag = "1")]
    pub layer: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "2")]
    pub billboard: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub hidden: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "4")]
    pub vertex_shader_asset: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub vertex_attributes: ::core::option::Option<VertexAttributes>,
    #[prost(string, optional, tag = "6")]
    pub pixel_shader_asset: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "7")]
    pub uniform_attributes: ::core::option::Option<UniformAttributes>,
    #[prost(string, optional, tag = "8")]
    pub mesh_asset: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "9")]
    pub textures: ::prost::alloc::vec::Vec<Texture>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneElement {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(message, optional, tag = "2")]
    pub draw_bundle: ::core::option::Option<DrawBundle>,
    #[prost(enumeration = "UpdateType", optional, tag = "3")]
    pub update_type: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneUpdate {
    #[prost(uint64, tag = "1")]
    pub index: u64,
    #[prost(message, optional, tag = "2")]
    pub shared_attributes: ::core::option::Option<UniformAttributes>,
    #[prost(message, repeated, tag = "3")]
    pub elements: ::prost::alloc::vec::Vec<SceneElement>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UpdateType {
    Full = 0,
    Increment = 1,
}
impl UpdateType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            UpdateType::Full => "Full",
            UpdateType::Increment => "Increment",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Full" => Some(Self::Full),
            "Increment" => Some(Self::Increment),
            _ => None,
        }
    }
}
