[package]
name = "game_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
proto_gen = { path = "../../build_util/proto_gen" }