/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Game configuration.
 */
export interface GameConfig {
  /**
   * Path for the game to start. Make sure game exists in game mapping file on the server.
   */
  game_id?: string;
  [k: string]: unknown;
}
