[package]
name = "test_game_host_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "*", features = ["json"] }
rocket_ws = "*"

game_host_server = { path = "../game_host_server" }
